-- 2026-08-13_003_create_password_resets.sql
-- One-time password reset codes. Generated by an admin via /api/auth/forgot,
-- consumed by /api/auth/reset. The plaintext code is returned ONCE in the
-- /api/auth/forgot response and never stored; only its bcrypt hash is kept.
-- All access is via the service-role key (RLS denies direct table access).

CREATE TABLE IF NOT EXISTS password_resets (
  id BIGSERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_password_resets_user_active
  ON password_resets (user_id, expires_at)
  WHERE used_at IS NULL;

ALTER TABLE password_resets ENABLE ROW LEVEL SECURITY;
-- No policies: the API uses SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.